version: '3'

# WIP
# services need to be configured. Those services also need to be monitored by ELK stack.
# 1. Jenkins : 9080
# 2. Nexus : 9081
# 3. SonarQube : 9000 / 9092
# 4. Mysql : 9306
# 5. phpmyadmin : 9180
# 6. Elastic Search : TBD
# 7. Logstash : TBD
# 8. Kibana : TBD

services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    labels:
      kompose.service.type: nodeport
    ports:
      - '9080:8080'
      - '50000:50000'
    volumes:
      - './jenkins/var/jenkins_home:/var/jenkins_home'
  nexus:
    image: 'sonatype/nexus3'
    container_name: nexus
    ports:
      - '9081:8081'
    volumes:
      - './nexus/nexus-data:/nexus-data'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - '9180:80'
    volumes:
     - './phpmyadmin/sessions:/sessions'
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    restart: always
    ports:
      - '9306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=sdlc
      - MYSQL_PASSWORD=sldc1234
      - MYSQL_DATABASE=sonar
    volumes:
      - './mysql/var/lib/mysql:/var/lib/mysql'
      - './mysql/etc/mysql:/etc/mysql'
  sonarqube:
    depends_on:
      - mysql
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=sdlc
      - SONARQUBE_JDBC_PASSWORD=sdlc1234
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    volumes:
      - './sonarqube/opt/sonarqube/conf:/opt/sonarqube/conf'
      - './sonarqube/opt/sonarqube/data:/opt/sonarqube/data'
      - './sonarqube/opt/sonarqube/extensions:/opt/sonarqube/extensions'
      - './sonarqube/opt/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins'